"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 09:29:07.072938
"""
from alembic import op
import sqlalchemy as sa
import app.db.session


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('access_token', sa.String(length=128), nullable=True),
    sa.Column('token_date', sa.Date(), nullable=True),
    sa.Column('updated_at', app.db.session.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('indicator_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('ts', app.db.session.UTCDateTime(timezone=True), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('pdm', sa.Float(), nullable=True),
    sa.Column('mdm', sa.Float(), nullable=True),
    sa.Column('pdi', sa.Float(), nullable=True),
    sa.Column('mdi', sa.Float(), nullable=True),
    sa.Column('dx', sa.Float(), nullable=True),
    sa.Column('adx', sa.Float(), nullable=True),
    sa.Column('tr_sum', sa.Float(), nullable=False),
    sa.Column('pdm_sum', sa.Float(), nullable=False),
    sa.Column('mdm_sum', sa.Float(), nullable=False),
    sa.Column('dx_sum', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'period', 'ts', name='uq_indicator')
    )
    with op.batch_alter_table('indicator_values', schema=None) as batch_op:
        batch_op.create_index('ix_indicator_lookup', ['symbol', 'timeframe', 'period', 'ts'], unique=False)

    op.create_table('market_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('ts', app.db.session.UTCDateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('created_at', app.db.session.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'ts', name='uq_candle')
    )
    with op.batch_alter_table('market_candles', schema=None) as batch_op:
        batch_op.create_index('ix_candle_lookup', ['symbol', 'timeframe', 'ts'], unique=False)

    op.create_table('strategy_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', app.db.session.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', app.db.session.UTCDateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index('ix_system_events_ts', ['ts'], unique=False)

    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=8), nullable=False),
    sa.Column('candle_ts', app.db.session.UTCDateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=48), nullable=True),
    sa.Column('started_at', app.db.session.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', app.db.session.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('config_version', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['strategy_configurations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_table('signal_setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('breakout_ts', app.db.session.UTCDateTime(timezone=True), nullable=False),
    sa.Column('detected_at', app.db.session.UTCDateTime(timezone=True), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('config_version', sa.String(length=16), nullable=False),
    sa.Column('breakout', sa.JSON(), nullable=False),
    sa.Column('signal_ts', app.db.session.UTCDateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('entry_atr', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('signal_context', sa.JSON(), nullable=True),
    sa.Column('peak_adx', sa.Float(), nullable=True),
    sa.Column('adx_declines', sa.Integer(), nullable=False),
    sa.Column('last_evaluated_ts', app.db.session.UTCDateTime(timezone=True), nullable=True),
    sa.Column('exit_ts', app.db.session.UTCDateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=40), nullable=True),
    sa.Column('closed_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', app.db.session.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.session.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['strategy_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_setups', schema=None) as batch_op:
        batch_op.create_index('ix_setup_symbol_state', ['symbol', 'state'], unique=False)

    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('candle_ts', app.db.session.UTCDateTime(timezone=True), nullable=True),
    sa.Column('adx5', sa.Float(), nullable=True),
    sa.Column('pdi5', sa.Float(), nullable=True),
    sa.Column('mdi5', sa.Float(), nullable=True),
    sa.Column('adx15', sa.Float(), nullable=True),
    sa.Column('pdi15', sa.Float(), nullable=True),
    sa.Column('mdi15', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('atr_status', sa.String(length=10), nullable=True),
    sa.Column('vix', sa.Float(), nullable=True),
    sa.Column('vix_change_pct', sa.Float(), nullable=True),
    sa.Column('gate1', sa.String(length=8), nullable=False),
    sa.Column('gate2', sa.String(length=8), nullable=False),
    sa.Column('atr_filter', sa.String(length=8), nullable=False),
    sa.Column('vix_filter', sa.String(length=8), nullable=False),
    sa.Column('final_result', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=True),
    sa.Column('rejection_reason', sa.String(length=200), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('config_version', sa.String(length=16), nullable=False),
    sa.Column('setup_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.session.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.ForeignKeyConstraint(['setup_id'], ['signal_setups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_run_id', 'symbol', name='uq_scan_symbol')
    )
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.create_index('ix_scan_results_symbol_ts', ['symbol', 'candle_ts'], unique=False)

    op.create_table('signal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setup_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('candle_ts', app.db.session.UTCDateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', app.db.session.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['setup_id'], ['signal_setups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_events_setup_id'), ['setup_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setup_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('entry_ts', app.db.session.UTCDateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_ts', app.db.session.UTCDateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=40), nullable=True),
    sa.Column('risk_points', sa.Float(), nullable=True),
    sa.Column('pnl_points', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('holding_minutes', sa.Float(), nullable=True),
    sa.Column('config_version', sa.String(length=16), nullable=False),
    sa.Column('breakout_adx_change', sa.Float(), nullable=True),
    sa.Column('adx5_entry', sa.Float(), nullable=True),
    sa.Column('adx15_entry', sa.Float(), nullable=True),
    sa.Column('atr_status', sa.String(length=10), nullable=True),
    sa.Column('vix_entry', sa.Float(), nullable=True),
    sa.Column('created_at', app.db.session.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['setup_id'], ['signal_setups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setup_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_events_setup_id'))

    op.drop_table('signal_events')
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_results_symbol_ts')

    op.drop_table('scan_results')
    with op.batch_alter_table('signal_setups', schema=None) as batch_op:
        batch_op.drop_index('ix_setup_symbol_state')

    op.drop_table('signal_setups')
    op.drop_table('scan_runs')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index('ix_system_events_ts')

    op.drop_table('system_events')
    op.drop_table('strategy_configurations')
    with op.batch_alter_table('market_candles', schema=None) as batch_op:
        batch_op.drop_index('ix_candle_lookup')

    op.drop_table('market_candles')
    with op.batch_alter_table('indicator_values', schema=None) as batch_op:
        batch_op.drop_index('ix_indicator_lookup')

    op.drop_table('indicator_values')
    op.drop_table('broker_sessions')
    # ### end Alembic commands ###
